### ISSUE TITLE
DC更新后显示乱码

### ISSUE THREAD

**Issue by skyerpe** [Mesagisto/discord-message-source#2]
由于控制台无法显示大部分中文，导致有部分中文显示乱码，希望改进

**Comment by Itsusinn** [comment]
@skyerpe 请问您是在使用windows吗

**Comment by skyerpe** [comment]
> @skyerpe 请问您是在使用windows吗

yes

**Comment by Itsusinn** [comment]
尝试 https://cloud.tencent.com/developer/article/1835811
